route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 2s
  group_interval: 3s
  repeat_interval: 10s
  receiver: scale-up
  routes:
  - match:
      service: server
      receiver: scale-up
      severity: major
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'scale-up'
  webhook_configs:
    - url: http://server:8080/system/alert
      send_resolved: true