global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'faas-monitor'

rule_files:
    - 'alert.rules.yml'
scrape_configs:
  
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "server"
    metrics_path: '/'
    scrape_interval: 2s
    dns_sd_configs:
      - names: ['tasks.server']
        port: 8000
        type: A
        refresh_interval: 5s



alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093